### PR TITLE
Extra export options and nicegui 'native'

### PR DESCRIPTION
**Pull request by mattman107**
1. Added export from the webgui
2. Added scheduled export functionality.
3. Added access to nicegui 'native' mode. Could use this and pyinstaller to make/package 'native' versions of the app, instead of forcing a web service.

### CODE REVIEW

**Comment by h-quer** [comment]
Looks fine, but why re-load the config on ui refresh and display ui? The ui refresh gets called quite often, re-loading the config every time seems a bit much?

**Comment by mattman107** [comment]
I might have went a bit gung-ho on that. 

I noticed sometimes I would load the webgui and the 'Scheduled Export' switch would be set in its default of False even though in the config.ini file it was set to True. So to make sure everything was always  up to date, I added those couple of re-loads. Let me do some more testing to see which ones if any are actually required.

**Comment by mattman107** [comment]
You are 100% right. Like I said I added those to help me debug why I was getting inconsistencies with the switch sometimes being enabled or disabled when it shouldn't have been. After removing them and testing a bit, I must have fixed the bug in my logic causing the inconsistencies. I have removed the extra config reloads.

**Comment by h-quer** [comment]
The container isn't building because it doesn't find a PyQt version to satisfy the requirements.txt.

**Comment by mattman107** [comment]
Let me double check the required ones for the nicegui 'native' mode.

**Comment by h-quer** [comment]
I've noticed that the PR somehow broke dark mode detection for the table view. Fixing it to light or dark mode in the settings still works, but the intermediate auto detection based on browser setting doesn't any more. Not exactly sure what caused it yet, will do some further testing when time permits.

**Comment by mattman107** [comment]
> I've noticed that the PR somehow broke dark mode detection for the table view. Fixing it to light or dark mode in the settings still works, but the intermediate auto detection based on browser setting doesn't any more. Not exactly sure what caused it yet, will do some further testing when time permits.

This has to do with the function dark_table if I am reading this right. I'm not sure exactly what would have broken this functionality in this PR, but I could see something from the [config update](https://github.com/h-quer/Slaanesh/pull/52) causing this issue. I'm pretty sure I got it in my most recent update there.

**Pull request merged**
